//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasGamePlayer1.DamasGamePlayer2Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DamasGamePlayer2Service.IDamasGamePlayer2Service")]
    public interface IDamasGamePlayer2Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDamasGamePlayer2Service/Play", ReplyAction="http://tempuri.org/IDamasGamePlayer2Service/PlayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IDamasGamePlayer2Service/PlayFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        void Play(DamasGame.Entities.Move move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDamasGamePlayer2Service/Play", ReplyAction="http://tempuri.org/IDamasGamePlayer2Service/PlayResponse")]
        System.Threading.Tasks.Task PlayAsync(DamasGame.Entities.Move move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDamasGamePlayer2Service/StartGame", ReplyAction="http://tempuri.org/IDamasGamePlayer2Service/StartGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IDamasGamePlayer2Service/StartGameFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        void StartGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDamasGamePlayer2Service/StartGame", ReplyAction="http://tempuri.org/IDamasGamePlayer2Service/StartGameResponse")]
        System.Threading.Tasks.Task StartGameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDamasGamePlayer2ServiceChannel : DamasGamePlayer1.DamasGamePlayer2Service.IDamasGamePlayer2Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DamasGamePlayer2ServiceClient : System.ServiceModel.ClientBase<DamasGamePlayer1.DamasGamePlayer2Service.IDamasGamePlayer2Service>, DamasGamePlayer1.DamasGamePlayer2Service.IDamasGamePlayer2Service {
        
        public DamasGamePlayer2ServiceClient() {
        }
        
        public DamasGamePlayer2ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DamasGamePlayer2ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DamasGamePlayer2ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DamasGamePlayer2ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Play(DamasGame.Entities.Move move) {
            base.Channel.Play(move);
        }
        
        public System.Threading.Tasks.Task PlayAsync(DamasGame.Entities.Move move) {
            return base.Channel.PlayAsync(move);
        }
        
        public void StartGame() {
            base.Channel.StartGame();
        }
        
        public System.Threading.Tasks.Task StartGameAsync() {
            return base.Channel.StartGameAsync();
        }
    }
}
