//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasGame.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DamasGame.Util.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando jogada do vermelho..
        /// </summary>
        public static string MSG_AGUARDANDO_JOGADA_VERMELHO {
            get {
                return ResourceManager.GetString("MSG_AGUARDANDO_JOGADA_VERMELHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando {0}....
        /// </summary>
        public static string MSG_AGUARDANDO_JOGADOR {
            get {
                return ResourceManager.GetString("MSG_AGUARDANDO_JOGADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando jogada do jogador 1..
        /// </summary>
        public static string MSG_AGUARDANDO_JOGADOR_1 {
            get {
                return ResourceManager.GetString("MSG_AGUARDANDO_JOGADOR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando jogada do jogador 2..
        /// </summary>
        public static string MSG_AGUARDANDO_JOGADOR_2 {
            get {
                return ResourceManager.GetString("MSG_AGUARDANDO_JOGADOR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voce deve comer a peça.
        /// </summary>
        public static string MSG_COMER_PECA {
            get {
                return ResourceManager.GetString("MSG_COMER_PECA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexão perdida com o jogador {0}..
        /// </summary>
        public static string MSG_CONEXAO_PERDIDA {
            get {
                return ResourceManager.GetString("MSG_CONEXAO_PERDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro na conexão com o {0}. Exception: {1}.
        /// </summary>
        public static string MSG_ERRO_GENERICA {
            get {
                return ResourceManager.GetString("MSG_ERRO_GENERICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é o vencedor! Deseja jogar novamente?.
        /// </summary>
        public static string MSG_FIM_JOGO {
            get {
                return ResourceManager.GetString("MSG_FIM_JOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando servidor jogador 1..
        /// </summary>
        public static string MSG_INICIANDO_SERVIDOR_JOGADOR1 {
            get {
                return ResourceManager.GetString("MSG_INICIANDO_SERVIDOR_JOGADOR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando servidor jogador 2..
        /// </summary>
        public static string MSG_INICIANDO_SERVIDOR_JOGADOR2 {
            get {
                return ResourceManager.GetString("MSG_INICIANDO_SERVIDOR_JOGADOR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogada do {0} realizada com sucesso..
        /// </summary>
        public static string MSG_JOGADA_COMPLETA {
            get {
                return ResourceManager.GetString("MSG_JOGADA_COMPLETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimento invalido. Tente novamente..
        /// </summary>
        public static string MSG_MOVIMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("MSG_MOVIMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preto joga.
        /// </summary>
        public static string MSG_PRETO_JOGA {
            get {
                return ResourceManager.GetString("MSG_PRETO_JOGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebida chamada remota do {0}..
        /// </summary>
        public static string MSG_RECEBIMENTO_CHAMADA {
            get {
                return ResourceManager.GetString("MSG_RECEBIMENTO_CHAMADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor iniciado..
        /// </summary>
        public static string MSG_SERVIDOR_INICIADO {
            get {
                return ResourceManager.GetString("MSG_SERVIDOR_INICIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vermelho joga.
        /// </summary>
        public static string MSG_VERMELHO_JOGA {
            get {
                return ResourceManager.GetString("MSG_VERMELHO_JOGA", resourceCulture);
            }
        }
    }
}
